name: ApplicationsWithFixture
testcases:
- name: ApplicationFromDump
  steps:
  # Dump API data  before executing this test case
  - name: Store ~original dump of hub data
    type: hub-fixture-store
    title: temp-clean

 # Load test data dump for this test case (sample-application)
  - name: Load fixture for this test
    type: hub-fixture-load
    title: sample-application

  # Execute the test
  - name: Check the sample application
    type: hub-api
    path: applications/1
    assertions:
    - result.bodyjson.name ShouldEqual tackle-testapp

  # Reload the API data with pre-this test case dump
  - name: Load fixture
    type: hub-fixture-load
    title: temp-clean
