name: ApplicationsAnalyzeTest
vars:
  applications:
  #- app: { # QE's, redirect failed
  #    "name": "book-server",
  #    "repository": {
  #      "kind": "git",
  #      "url": "https://github.com/ibraginsky/book-server"
  #    }
  #  }
  #  addon_name: windup
  #  task_data: {
  #    "app_name": "book-server",
  #    "targets": [
  #      "cloud-readiness"
  #    ],
  #    "story_points": 5
  #  }
  #- app: {  # QE's, fatal: could not read Username for 'https://github.com': No such device or address",
  #    "name": "tackle-testapp",
  #    "identities": [],
  #    "repository": {
  #      "kind": "git",
  #      "url": "https://github.com/konveyor/tackle-testapp"
  #    }
  #  }
  #  addon_name: windup
  #  task_data: {
  #    "app_name": "tackle-testapp",
  #    "targets": [
  #      "cloud-readiness"
  #    ],
  #    "story_points": 1
  #  }
  - app: {  # David's tackle2-addon-windup e2e test
      "name":"Pathfinder",
      "description": "Tackle Pathfinder application.",
      "repository": {
        "name": "tackle-pathfinder",
        "url": "https://github.com/konveyor/tackle-pathfinder.git",
        "branch": "1.2.0" }
    }
    addon_name: windup
    task_data: {
      "mode": {
          "artifact": "",
          "binary": false,
          "withDeps": false,
          "diva": true
      },
      "output": "/windup/report",
      "rules": {
          "path": "",
          "tags": {
              "excluded": [ ]
          }
      },
      "scope": {
          "packages": {
              "excluded": [ ],
              "included": [ ]
          },
          "withKnown": false
      },
      "sources": [ ],
      "targets": [
          "cloud-readiness"
      ]
    }

testcases:
- name: ApplicationsAnalysis 
  steps:
  - name: Bulk application analysis
    type: application-analyze-test
    range: '{{.applications}}'
    app: '{{.value.app}}'
    task_data: "{{.value.task_data}}"
    addon_name: "{{.value.addon_name}}"
