name: ApplicationsTestTable
vars:
  applications:
  # Valid application,    Note: >- block must not end with comment (or start with "{") and the intendation of comments matters!
  - input: {
      "name": "tackle-testapp",
      "identities": [],
      "repository": {
        "kind": "git",
        "url": "https://github.com/konveyor/tackle-testapp"
      }
    }
    expectedStatus: 201
    shouldError: false

  # Invalid - empty name
  - input: {
      "name": ""
    }
    expectedStatus: 400
    shouldError: true

testcases:
- name: ApplicationsCreate 
  steps:
  # This calls create/get and delete application in reusable test/executor from lib/application-create-test.yml
  - name: Bulk create application
    type: application-create-test
    range: '{{.applications}}'
    application: '{{.value.input}}'
    expectedStatus: "{{.value.expectedStatus}}"
    shouldError: "{{.value.shouldError}}"
