name: E2E API Test

on:
  schedule:
    - cron: '1 0,12 * * *' # Regulary every 12 hours
  push:
    branches: [ "main" ]  # After CI code update
    paths-ignore:
      - '**.md'

jobs:
  test-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
      - uses: actions/checkout@v3
      - name: start-minikube
        uses: konveyor/tackle2-operator/.github/actions/start-minikube@main
      - name: install-tackle
        uses: konveyor/tackle2-operator/.github/actions/install-tackle@main
        #with:
        #  tackle-addon-windup-image: quay.io/konveyor/tackle2-addon-windup:${{ github.sha }}
        #  tackle-image-pull-policy: IfNotPresent
      - name: Run End-to-End API Tests
        run: |
          make init
          make test-e2e
